# Final Project: Integrated Data Analysis Project
## Subject: Homelessness

The goal is to analyze homeless shelters across the U.S. to identify areas and times that need additional resources and shelter development, along with the costs of such development.

## Importing Libraries

In [1]:
import pandas as pd

## Data Sourcing

I found this dataset by searching for homelessness datasets in Kaggle:

https://www.kaggle.com/datasets/shamimhasan8/homelessness-and-shelter-data

There are various websites that show prices of available land in certain regions. This dataset provides a good aggregation of land prices across the entire U.S:

https://www.aei.org/housing/land-price-indicators/

In [11]:
shelters = pd.read_csv("homelessness_shelter_data.csv")
res_land_price = pd.read_excel("AEI_adjusted-Land-Data-2024-1.xlsx", sheet_name="CBSA")

## Data Preparation and Integration
### Exploratory Data Analysis
#### Overview of the Dataframes' Features

In [12]:
shelters.head()

,id,date,shelter_name,city,state,total_capacity,occupied_beds,available_beds,occupancy_rate,average_age,male_percentage,female_percentage,season,notes
0,1,2023-10-05,Sunrise Shelter,Dallas,TX,85,62,23,72.9,19,43,57,Spring,High demand
1,2,2023-08-01,Safe Haven,Dallas,TX,128,117,11,91.4,58,45,55,Summer,No issues reported
2,3,2025-04-27,Second Chance,San Jose,CA,190,144,46,75.8,56,52,48,Summer,Excellent condition
3,4,2024-10-05,Harbor Home,San Jose,CA,115,7,108,6.1,63,48,52,Autumn,Needs maintenance
4,5,2024-09-15,Harbor Home,San Antonio,TX,155,65,90,41.9,21,48,52,Summer,No issues reported

In [13]:
res_land_price.head()

,CBSA,CBSA Code,Year,"Land Value (Per Acre, As-Is)","Land Value (1/4 Acre Lot, Standardized)",Land Share of Property Value,Home Price Appreciation (HPA)
0,"Aberdeen, SD",10100,2012,72000,21800,0.122,1.000
1,"Aberdeen, SD",10100,2013,75900,23000,0.125,1.025
2,"Aberdeen, SD",10100,2014,62300,18900,0.101,1.037
3,"Aberdeen, SD",10100,2015,65100,19700,0.105,1.050
4,"Aberdeen, SD",10100,2016,98400,29800,0.150,1.105

CBSA stands for core-based statistical area. It is roughly equivalent to major cities. I plan to integrate shelters and land price on this feature.

https://en.wikipedia.org/wiki/List_of_core-based_statistical_areas

https://www.bls.gov/tus/dictionaries/gtcbsa_gtco_aug_2015.pdf

#### Checking for Missing Values

In [5]:
shelters.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1000 non-null   int64
 1   date               1000 non-null   str
 2   shelter_name       1000 non-null   str
 3   city               1000 non-null   str
 4   state              1000 non-null   str
 5   total_capacity     1000 non-null   int64
 6   occupied_beds      1000 non-null   int64
 7   available_beds     1000 non-null   int64
 8   occupancy_rate     1000 non-null   float64
 9   average_age        1000 non-null   int64
 10  male_percentage    1000 non-null   int64
 11  female_percentage  1000 non-null   int64
 12  season             1000 non-null   str
 13  notes              913 non-null    str
dtypes: float64(1), int64(7), str(6)
memory usage: 109.5 KB

All features of the shelters dataframe have non-null values except notes. I don't plan on analyzing the notes feature, so we can ignore that missing notes data. If I decide to recommend sentiment analysis of the notes for future research, then those missing values would need to be addressed.

In [14]:
res_land_price.info()

<class 'pandas.DataFrame'>
RangeIndex: 11206 entries, 0 to 11205
Data columns (total 7 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   CBSA                                     11206 non-null  str
 1   CBSA Code                                11206 non-null  int64
 2   Year                                     11206 non-null  int64
 3   Land Value (Per Acre, As-Is)             11206 non-null  int64
 4   Land Value (1/4 Acre Lot, Standardized)  11206 non-null  int64
 5   Land Share of Property Value             11206 non-null  float64
 6   Home Price Appreciation (HPA)            11206 non-null  float64
dtypes: float64(2), int64(4), str(1)
memory usage: 613.0 KB

All features of the residential land price dataframe have non-null values.

#### Overview of the Data Distributions

In [6]:
shelters.describe()

,id,total_capacity,occupied_beds,available_beds,occupancy_rate,average_age,male_percentage,female_percentage
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,179.123000,91.874000,87.249000,51.214700,42.037000,54.634000,45.366000
std,288.819436,73.419195,67.068937,65.531224,28.880331,13.768122,8.797468,8.797468
min,1.000000,50.000000,0.000000,0.000000,0.000000,18.000000,40.000000,30.000000
25%,250.750000,115.000000,38.000000,35.000000,26.775000,30.000000,47.000000,38.000000
50%,500.500000,182.000000,76.000000,71.000000,51.850000,42.000000,55.000000,45.000000
75%,750.250000,243.000000,136.000000,128.250000,76.800000,54.000000,62.000000,53.000000
max,1000.000000,300.000000,294.000000,296.000000,100.000000,65.000000,70.000000,60.000000

In [15]:
res_land_price.describe()

,CBSA Code,Year,"Land Value (Per Acre, As-Is)","Land Value (1/4 Acre Lot, Standardized)",Land Share of Property Value,Home Price Appreciation (HPA)
count,11206.000000,11206.000000,1.120600e+04,1.120600e+04,11206.000000,11206.000000
mean,29862.737819,2018.000000,2.538533e+05,8.811862e+04,0.315959,1.441001
std,11406.387273,3.741824,5.216632e+05,1.272137e+05,0.142970,0.449742
min,10100.000000,2012.000000,-9.230000e+04,-2.920000e+04,-0.298000,0.688000
25%,20020.000000,2015.000000,6.140000e+04,2.750000e+04,0.208000,1.086000
50%,29920.000000,2018.000000,1.182500e+05,5.010000e+04,0.296000,1.288000
75%,39780.000000,2021.000000,2.441000e+05,9.577500e+04,0.411000,1.693000
max,49820.000000,2024.000000,9.941600e+06,1.927200e+06,0.838000,3.555000