# Final Project: Integrated Data Analysis Project
Subject: Homelessness

By: Karl Isele

In [1]:
import pandas as pd

## Data Sourcing

In [2]:
shelters_df = pd.read_csv("homelessness_shelter_data.csv")

## Data Preparation and Integration
### Exploratory Data Analysis

In [4]:
shelters_df.head()

,id,date,shelter_name,city,state,total_capacity,occupied_beds,available_beds,occupancy_rate,average_age,male_percentage,female_percentage,season,notes
0,1,2023-10-05,Sunrise Shelter,Dallas,TX,85,62,23,72.9,19,43,57,Spring,High demand
1,2,2023-08-01,Safe Haven,Dallas,TX,128,117,11,91.4,58,45,55,Summer,No issues reported
2,3,2025-04-27,Second Chance,San Jose,CA,190,144,46,75.8,56,52,48,Summer,Excellent condition
3,4,2024-10-05,Harbor Home,San Jose,CA,115,7,108,6.1,63,48,52,Autumn,Needs maintenance
4,5,2024-09-15,Harbor Home,San Antonio,TX,155,65,90,41.9,21,48,52,Summer,No issues reported

Looking at the shelters dataframe info, all the features have non-null values except notes. I don't plan on analyzing the notes feature, so we can ignore that missing notes data. If I decide to recommend sentiment analysis of the notes for future research, then those missing values would need to be addressed.

In [5]:
shelters_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1000 non-null   int64
 1   date               1000 non-null   str
 2   shelter_name       1000 non-null   str
 3   city               1000 non-null   str
 4   state              1000 non-null   str
 5   total_capacity     1000 non-null   int64
 6   occupied_beds      1000 non-null   int64
 7   available_beds     1000 non-null   int64
 8   occupancy_rate     1000 non-null   float64
 9   average_age        1000 non-null   int64
 10  male_percentage    1000 non-null   int64
 11  female_percentage  1000 non-null   int64
 12  season             1000 non-null   str
 13  notes              913 non-null    str
dtypes: float64(1), int64(7), str(6)
memory usage: 109.5 KB

In [6]:
shelters_df.describe()

,id,total_capacity,occupied_beds,available_beds,occupancy_rate,average_age,male_percentage,female_percentage
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,179.123000,91.874000,87.249000,51.214700,42.037000,54.634000,45.366000
std,288.819436,73.419195,67.068937,65.531224,28.880331,13.768122,8.797468,8.797468
min,1.000000,50.000000,0.000000,0.000000,0.000000,18.000000,40.000000,30.000000
25%,250.750000,115.000000,38.000000,35.000000,26.775000,30.000000,47.000000,38.000000
50%,500.500000,182.000000,76.000000,71.000000,51.850000,42.000000,55.000000,45.000000
75%,750.250000,243.000000,136.000000,128.250000,76.800000,54.000000,62.000000,53.000000
max,1000.000000,300.000000,294.000000,296.000000,100.000000,65.000000,70.000000,60.000000